import { describe, it, expect, vi, beforeEach } from 'vitest'

// ─── Mock the sql driver before importing audit ───────────────────────────────
// vi.hoisted ensures mockSql is available when vi.mock factory runs (hoisted to top).
const { mockSql } = vi.hoisted(() => {
  return { mockSql: vi.fn() }
})

vi.mock('@/lib/db', () => ({
  sql: mockSql,
  generateId: () => 'test-id',
}))

import { writeAuditLog, type AuditAction } from '../audit'

// ─── Helpers ──────────────────────────────────────────────────────────────────

function makeEntry(overrides: Partial<Parameters<typeof writeAuditLog>[0]> = {}) {
  return {
    adminId: 'admin-123',
    action: 'ADMIN_TERMINATED' as AuditAction,
    targetType: 'attempt' as const,
    targetId: 'attempt-456',
    metadata: { reason: 'cheating suspected' },
    ...overrides,
  }
}

// ─── Tests ────────────────────────────────────────────────────────────────────

describe('writeAuditLog', () => {
  beforeEach(() => {
    vi.clearAllMocks()
    // Default: sql resolves successfully (simulates a tagged template literal call)
    mockSql.mockResolvedValue([])
  })

  it('calls sql with the correct INSERT fields for ADMIN_TERMINATED', async () => {
    const entry = makeEntry()
    await writeAuditLog(entry)

    expect(mockSql).toHaveBeenCalledOnce()

    // Verify the template literal was called — the first argument is the
    // TemplateStringsArray and subsequent args are the interpolated values.
    const callArgs = mockSql.mock.calls[0]
    // The interpolated values (after the template strings array) should include
    // all five fields in order: adminId, action, targetType, targetId, metadata
    const interpolated = callArgs.slice(1)
    expect(interpolated).toContain(entry.adminId)
    expect(interpolated).toContain(entry.action)
    expect(interpolated).toContain(entry.targetType)
    expect(interpolated).toContain(entry.targetId)
    // metadata is JSON-stringified
    expect(interpolated).toContain(JSON.stringify(entry.metadata))
  })

  it('calls sql with the correct INSERT fields for SCORE_OVERRIDE', async () => {
    const entry = makeEntry({
      action: 'SCORE_OVERRIDE',
      targetType: 'attempt',
      metadata: { previousScore: 40, newScore: 55 },
    })
    await writeAuditLog(entry)

    expect(mockSql).toHaveBeenCalledOnce()
    const interpolated = mockSql.mock.calls[0].slice(1)
    expect(interpolated).toContain('SCORE_OVERRIDE')
    expect(interpolated).toContain(JSON.stringify({ previousScore: 40, newScore: 55 }))
  })

  it('calls sql with the correct INSERT fields for RESULTS_UNPUBLISHED', async () => {
    const entry = makeEntry({
      action: 'RESULTS_UNPUBLISHED',
      targetType: 'quiz',
      targetId: 'quiz-789',
      metadata: { previousPublishedAt: '2025-01-15T10:30:00.000Z' },
    })
    await writeAuditLog(entry)

    expect(mockSql).toHaveBeenCalledOnce()
    const interpolated = mockSql.mock.calls[0].slice(1)
    expect(interpolated).toContain('RESULTS_UNPUBLISHED')
    expect(interpolated).toContain('quiz')
    expect(interpolated).toContain('quiz-789')
  })

  it('does NOT pass id or createdAt to the INSERT (they use DB defaults)', async () => {
    const entry = makeEntry()
    await writeAuditLog(entry)

    const interpolated = mockSql.mock.calls[0].slice(1)
    // None of the interpolated values should look like a UUID or Date
    // (id is generated by gen_random_uuid(), createdAt by DEFAULT NOW())
    for (const val of interpolated) {
      expect(typeof val).not.toBe('object') // no Date objects
    }
    // Specifically, there should be exactly 5 interpolated values:
    // adminId, action, targetType, targetId, metadata (as JSON string)
    expect(interpolated).toHaveLength(5)
  })

  it('does not throw when the sql call fails (non-fatal)', async () => {
    mockSql.mockRejectedValue(new Error('DB connection failed'))

    const entry = makeEntry()
    // Should resolve without throwing
    await expect(writeAuditLog(entry)).resolves.toBeUndefined()
  })

  it('logs an error to console when the sql call fails', async () => {
    const consoleSpy = vi.spyOn(console, 'error').mockImplementation(() => {})
    mockSql.mockRejectedValue(new Error('DB connection failed'))

    await writeAuditLog(makeEntry())

    expect(consoleSpy).toHaveBeenCalledOnce()
    expect(consoleSpy.mock.calls[0][0]).toContain('[audit]')

    consoleSpy.mockRestore()
  })

  it('handles empty metadata object correctly', async () => {
    const entry = makeEntry({ metadata: {} })
    await writeAuditLog(entry)

    const interpolated = mockSql.mock.calls[0].slice(1)
    expect(interpolated).toContain('{}')
  })

  it('handles metadata with nested objects', async () => {
    const metadata = { previousScore: 42, newScore: 50, reason: null }
    const entry = makeEntry({ action: 'SCORE_OVERRIDE', metadata })
    await writeAuditLog(entry)

    const interpolated = mockSql.mock.calls[0].slice(1)
    expect(interpolated).toContain(JSON.stringify(metadata))
  })
})
